; PHPVM profile preset: laravel
; Managed by phpvm — edit freely. Switch with `phpvm profile use laravel`.

memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
display_errors = On
error_reporting = E_ALL

extension=curl
extension=iconv
extension=intl
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=session
extension=simplexml
extension=tokenizer
extension=xml
extension=zip